---
- name: Verify variables
  ansible.builtin.include_tasks: assert.yml

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define nut_packages.
  ansible.builtin.set_fact:
    nut_packages: "{{ __nut_packages | list }}"
  when: nut_packages is not defined

- name: Configure NUT
  ansible.builtin.include_tasks: configure.yml
  when: nut_state == 'present' and nut_managed_config

- name: Install NUT via package manager
  ansible.builtin.include_tasks: install_managed.yml
  when: nut_state == 'present' and not nut_install_from_source

- name: Install or uninstall NUT from source
  ansible.builtin.include_tasks: manage_install_from_source.yml
  when: nut_install_from_source   

- name: Uninstall NUT via package manager
  ansible.builtin.include_tasks: uninstall_managed.yml
  when: nut_state == 'absent' and not nut_install_from_source

- name: Remove NUT configuration
  ansible.builtin.include_tasks: unconfigure.yml
  when: nut_state == 'absent' and nut_managed_config
