---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Verify variables
  ansible.builtin.include_tasks: assert.yml

- name: Define nut_packages.
  ansible.builtin.set_fact:
    nut_packages: "{{ __nut_packages | list }}"
  when: nut_packages is not defined

- name: Install NUT via package manager
  ansible.builtin.include_tasks: install_managed.yml
  when: nut_state == 'present' and not nut_install_from_source

- name: Install or uninstall NUT from source
  ansible.builtin.include_tasks: manage_install_from_source.yml
  when: nut_state == 'present' and nut_install_from_source

- name: Configure NUT services
  ansible.builtin.include_tasks: service.yml
  when: nut_state == "present"

- name: Uninstall NUT via package manager
  ansible.builtin.include_tasks: uninstall.yml
  when: nut_state == 'absent'

- name: Remove NUT configuration
  ansible.builtin.include_tasks: unconfigure.yml
  when: nut_state == 'absent' and nut_managed_config
