---
- name: Get installed NUT services
  ansible.builtin.include_tasks: get_installed_nut_services.yml
  when: nut_enable_service

- name: "Restart nut."
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ nut_services_installed | map(attribute='name') | list | difference(['nut-driver.service', 'nut-driver@.service']) }}"
  when: nut_enable_service
