---
- name: Get installed NUT services
  ansible.builtin.include_tasks: get_installed_nut_services.yml
  when: nut_enable_service

- name: "Restart nut."
  ansible.builtin.include_tasks: restart_service.yml
  loop_control:
    loop_var: service_name
  loop: "{{ nut_services_installed | map(attribute='name') | list | difference(['nut-driver@.service']) }}"
  when: nut_enable_service
