---
- name: Determine service unit file
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
  register: service_status

- name: "Restart service."
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted
    enabled: true
  when:
    - service_status.status['LoadState'] != 'not-found'
    - service_status.status['LoadState'] != 'masked'
