# This task removes the NUT configuration files
---
- name: Remove NUT configuration files
  ansible.builtin.file:
    path: /etc/nut
    state: absent
  when: nut_state == 'absent' and nut_managed_config

- name: Ensure NUT user is removed
  ansible.builtin.user:
    name: nut
    group: nut
    state: absent

- name: Ensure NUT group is removed
  ansible.builtin.group:
    name: nut
    state: absent
