# This task removes the NUT configuration files
---
- name: Remove NUT configuration files
  ansible.builtin.file:
    path: /etc/nut
    state: absent
  when: nut_state == 'absent' and nut_managed_config
  