---
- name: Remove NUT packages
  ansible.builtin.apt:
    purge: true
    name: "{{ nut_packages }}"
    state: absent

- name: Perform autoremove (to remove libupsclient6)
  ansible.builtin.apt:
    autoremove: true
