---
- name: Remove NUT via package manager
  ansible.builtin.package:
    name: "{{ nut_packages }}"
    state: absent
  
- name: Perform autoremove (to remove libupsclient6)
  ansible.builtin.apt:
    autoremove: true