---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify communication with dummy_ups
      ansible.builtin.command:
        argv:
          - upsc
          - dummy_ups

    - name: Perform command on dummy_ups with monitor user
      ansible.builtin.command:
        argv:
          - upscmd
          - -u monitor
          - -p changeme
          - dummy_ups
          - load.off
      ignore_errors: true
      register: upscmd_result

    - name: Assert upscmd for monitor user on dummy_ups was denied
      ansible.builtin.assert:
        that:
          - upscmd_result.rc == 1
          - "'ACCESS-DENIED' in upscmd_result.stderr"

    - name: Perform command on dummy_ups2 with monitor user
      ansible.builtin.command:
        argv:
          - upscmd
          - -u monitor
          - -p changeme
          - dummy_ups2
          - load.off
      ignore_errors: true
      register: upscmd_result

    - name: Assert upscmd for monitor user  on dummy_ups2 was denied
      ansible.builtin.assert:
        that:
          - upscmd_result.rc == 1
          - "'ACCESS-DENIED' in upscmd_result.stderr"

    - name: Verify communication with dummy_ups2
      ansible.builtin.command:
        argv:
          - upsc
          - dummy_ups2

    - name: Perform command on dummy_ups with second_user user
      ansible.builtin.command:
        argv:
          - upscmd
          - -u second_user
          - -p insecure_password
          - dummy_ups
          - load.off

    - name: Perform command on dummy_ups2 with second_user user
      ansible.builtin.command:
        argv:
          - upscmd
          - -u second_user
          - -p insecure_password
          - dummy_ups2
          - load.off
