---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather installed services
      ansible.builtin.service_facts:

    - name: Verify NUT services are running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['nut-monitor.service'] is defined
          - ansible_facts.services['nut-monitor.service'].state == 'running'
          - ansible_facts.services['nut-server.service'] is not defined 
            or ansible_facts.services['nut-server.service'].status == 'not-found'

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Verify NUT packages are installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['nut-client'] is defined
          - ansible_facts.packages['nut-server'] is not defined
