---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Create NUT configuration folder.
      ansible.builtin.file:
        path: "/etc/nut"
        state: directory
        mode: '0755'
    - name: Copy dummy-ups.dev file
      ansible.builtin.copy:
        src: "../dummy-ups.dev"
        dest: "/etc/nut/dummy-ups.dev"
        mode: '0755'
  roles:
    - role: nut
      nut_install_from_source: true
      nut_source_tag: v2.8.2
      nut_drivers:
        - dummy-ups
      nut_users:
        - name: monitor
          password: changeme
          role: secondary
      nut_ups:
        - name: dummy_ups
          monitoruser: monitor
          driver: dummy-ups
          device: /etc/nut/dummy-ups.dev
          description: "Dummy UPS for testing"
