---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify communication with dummy_ups
      ansible.builtin.command:
        argv:
          - upsc
          - dummy_ups

    - name: Perform command on dummy_ups with monitor user
      ansible.builtin.command:
        argv:
          - upscmd
          - -u monitor
          - -p changeme
          - dummy_ups
          - load.off

    - name: Get installed NUT version
      ansible.builtin.include_tasks: ../../tasks/get_installed_nut_version.yml

    - name: Verify installed version matches desired version
      ansible.builtin.assert:
        that:
          - nut_installed_version is defined
          - nut_installed_version == "v2.8.2"

    - name: Gather installed services
      ansible.builtin.service_facts:

    - name: Verify NUT services are running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['nut-monitor.service'] is defined
          - ansible_facts.services['nut-server.service'] is defined
          - ansible_facts.services['nut-monitor.service'].state == 'running'
          - ansible_facts.services['nut-server.service'].state == 'running'

    - name: Gather package facts
      ansible.builtin.package_facts:
      when: nut_installed_version is defined

    - name: Verify no NUT packages are installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['nut-client'] is not defined
          - ansible_facts.packages['nut-server'] is not defined
